# Generated by Django 5.2 on 2025-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course', models.CharField(default='Python', max_length=50)),
                ('Course_Level', models.CharField(default='Basic', max_length=50)),
                ('Level', models.CharField(max_length=50)),
                ('Topic', models.CharField(max_length=100)),
                ('Sub_Topic', models.CharField(max_length=100)),
                ('Question', models.TextField()),
                ('Options', models.TextField(max_length=255)),
                ('OptionA', models.CharField(max_length=255)),
                ('OptionB', models.CharField(max_length=255)),
                ('OptionC', models.CharField(max_length=255)),
                ('OptionD', models.CharField(max_length=255)),
                ('Answer_option', models.CharField(max_length=255)),
                ('Correct_answer', models.CharField(max_length=255)),
            ],
        ),
    ]
