# Generated by Django 5.2 on 2025-05-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question_bank',
            new_name='QuestionBank',
        ),
    ]
